### ISSUE TITLE
Curry.swift vs Curry.framework

### ISSUE THREAD

**Issue by paulyoung** [thoughtbot/Curry#11]
Argo recently started including `Runes.swift` instead of `Runes.framework`, which is awesome for people using Argo since it's one less framework to deal with _unless_ they're using Runes for other purposes.

Am I correct in thinking the same thing could be done for Curry, or is there something special Argo does with only including operator definitions for Runes?

If a framework included `Curry.swift` as a private dependency, a consumer of that framework should also be able to add `Curry.framework` (or `Curry.swift`, I suppose) without any conflicts, correct?

I'd love to leverage Curry as a private dependency in this way to alleviate the burden of dealing with yet another framework.

**Comment by gfontenot** [comment]
You _could_ do that, but I wouldn't recommend it. The difference is that Swift is totally fine with duplicate operator definitions, as long as they match and there aren't duplicate _implementations_. If you pulled in `Curry.swift` as an internal dependency, you'd also be providing it as part of your API, and then anyone using `Curry.framework` (or even anyone writing their own `curry` functions) would get errors about ambiguous functions.

It might be interesting to have an `internal` version of these functions that aren't linked into `Curry.framework` that users could then pull in as an internal dependency, but I also wonder if that would be overkill. For Argo, [we're just implementing the one version of `curry` that we need internally](https://github.com/thoughtbot/Argo/blob/master/Argo/Functions/curry.swift). We don't need to pull in the other 63.

**Comment by paulyoung** [comment]
Yeah, I hadn't considered that everything is `public` and I'd want it to be `internal`.

**Comment by paulyoung** [comment]
If we could change access control when importing I'd use this approach with a few different frameworks.

**Comment by gfontenot** [comment]
Oh yeah that'd be rad.

**Comment by paulyoung** [comment]
A glimmer of hope, maybe? https://github.com/typelift/SwiftCheck/pull/114/files#r44612923

**Comment by gfontenot** [comment]
I don't follow how that might help this? You'd have to _prevent_ the exporting of the various `curry` implementations, right?

**Comment by paulyoung** [comment]
Yeah, you're right. Even if everything was internal by default this probably would be much use either.
