### ISSUE TITLE
"Expression too complex" errors happening too often/quickly

### ISSUE THREAD

**Issue by gfontenot** [thoughtbot/Curry#15]
With the new syntax/arrity of `curry`, we seem to be hitting these complexity errors shockingly fast. Sometimes as quickly as 5 properties. This sucks. We should either:
1. Drop the number of `curry` functions to 26, since for _some_ reason that nearly doubles the number of applications we can perform
2. Suggest that users always save the curried method off to an intermediate variable, since that nearly triples the number of applications
3. All of the above.

**Comment by tonyd256** [comment]
related: http://www.cocoawithlove.com/blog/2016/07/12/type-checker-issues.html

**Comment by gtsifrikas** [comment]
Hello,
Could you please explain what do you mean by "number of applications"?
Also if you have a model with more than 21 properties in argo how can you handle it?
Thank you

**Comment by gfontenot** [comment]
> Could you please explain what do you mean by "number of applications"?

Yeah, I worded that oddly in the initial issue. I believe what I meant is that by saving the function off into an intermediate variable instead of using it directly, we can immediately jump to 15 properties without any issues.

> Also if you have a model with more than 21 properties in argo how can you handle it?

I'd suggest refactoring your models to try to reduce the number of properties on any one object, honestly. But I'd probably recommend that even if you _weren't_ hitting limitations with Curry.

**Comment by btc** [comment]
I'm hitting this error on `curry(FooStruct.init)` with just 6 properties.

**Comment by gfontenot** [comment]
@btc Can you give more detail? What are the 6 properties, and how are you using `curry`?

**Comment by btc** [comment]
@gfontenot 

This causes the error:

``` swift
struct NowPlayingInfo {
    let title: String
    let artist: String
    let album: String
    let stationTag: String
    let artworkDominantColor: String?
    let artworkUrl500: String?
}

extension NowPlayingInfo: Decodable {
    static func decode(_ j: JSON) -> Decoded<NowPlayingInfo> {
        return curry(self.init)
            <^> j <| "title"
            <*> j <| "artist"
            <*> j <| "album"
            <*> j <| "station-tag"
            <*> j <|? "artwork-dominant-color"
            <*> j <|? "artwork-url-500"
    }
}
```

However, if I decompose like this, it works:
``` swift

struct NowPlayingInfo {
    let title: String
    let artist: String
    let album: String
    let stationTag: String
    let artwork: Artwork

    // decomposed into another struct because of a limitation in the curry lib
    // see: https://github.com/thoughtbot/Argo/blob/master/Documentation/Curry-Limitations.md
    struct Artwork {
        let dominantColor: String?
        let url500: String?
    }
}

extension NowPlayingInfo: Decodable {
    static func decode(_ j: JSON) -> Decoded<NowPlayingInfo> {
        return curry(self.init)
            <^> j <| "title"
            <*> j <| "artist"
            <*> j <| "album"
            <*> j <| "station-tag"
            <*> NowPlayingInfo.Artwork.decode(j)
    }
}

extension NowPlayingInfo.Artwork: Decodable {
    static func decode(_ j: JSON) -> Decoded<NowPlayingInfo.Artwork> {
        return curry(self.init)
            <^> j <|? "artwork-dominant-color"
            <*> j <|? "artwork-url-500"
    }
}

```

**Comment by gfontenot** [comment]
Interesting. That's compiling fine for me locally. What versions of Argo/Curry/Xcode are you using?

**Comment by btc** [comment]
Does this error depend on the compute power of the system on which the compiler is running? 

I wonder where it's a function of time (timeout) or a function of problem size (threshold).

Xcode 8.2.1
Curry 3.0.0
Argo 4.1.1
Runes 4.0.1

![image](https://cloud.githubusercontent.com/assets/734339/21582470/7e2779fc-d00d-11e6-946d-cc1ce5048347.png)

**Comment by gfontenot** [comment]
I'm not sure, honestly. I will say that my machine is an older 15" MBP with a slower processor (2.5 GHz Core i7) and is otherwise identical, so I'm not totally sure that's the case.

**Comment by gfontenot** [comment]
I'm going to go ahead and close this due to inactivity but please feel free to reopen if this is still an issue.
