### ISSUE TITLE
Removal of curried function declaration syntax

### ISSUE THREAD

**Issue by paulyoung** [thoughtbot/Curry#18]
I imagine we'd want to update `generator.swift` in response to this change: https://github.com/apple/swift-evolution/blob/master/proposals/0002-remove-currying.md

![image](https://cloud.githubusercontent.com/assets/84700/11764720/621d3a44-a133-11e5-9331-7ef37e3e2186.jpeg)

**Comment by paulyoung** [comment]
Related: https://twitter.com/jckarter/status/675854346123280389

**Comment by gfontenot** [comment]
Yep, we need to do this. I've been meaning to get to this, but haven't had time. I'm going to add the help wanted label.

**Comment by tonyd256** [comment]
Damn! I was so proud of this too. Oh well, as long as currying isn't going away then I'm happy.

**Comment by gfontenot** [comment]
Made this change in #19
