### ISSUE TITLE
Deprecated syntax

### ISSUE THREAD

**Issue by sharoni** [thoughtbot/Curry#21]
Current currying `func` declaration syntax will be deprecated -- https://github.com/apple/swift-evolution/blob/master/proposals/0002-remove-currying.md

**Comment by ManWithBear** [comment]
So? Will you continue work on this lib? Or you will stop support it, when swift 3 will be released?

**Comment by gfontenot** [comment]
We already support the supported syntax for swift 3. We're not going anywhere.
