### ISSUE TITLE
Make Curry release for new syntax?

### ISSUE THREAD

**Issue by mbrandonw** [thoughtbot/Curry#22]
Anything stopping y'all from making a new release with the preferred Swift 2.2 syntax?

Wanted to update Argo to get rid of some warnings in my projects.

Thanks!

**Comment by gfontenot** [comment]
Nothing whatsoever! Thanks for the reminder!

2.0 is now available via your dependency manager of choice.

**Comment by mbrandonw** [comment]
awwww yeahhhh, thanks @gfontenot!
