### ISSUE TITLE
Warnings: "extraneous '_' in parameter

### ISSUE THREAD

**Issue by JRHeaton** [thoughtbot/Curry#28]
Howdy! I'm posting this in case the author(s) are unaware that with the Swift 2.x toolchains, there are currently warnings on each function decl regarding the first parameter label. 
Example:

```
~proj/Carthage/Checkouts/Curry/Source/Curry.swift:1:25: warning: extraneous '_' in parameter: 'function' has no keyword argument name
~proj/Carthage/Checkouts/Curry/Source/Curry.swift:5:28: warning: extraneous '_' in parameter: 'function' has no keyword argument name
~proj/Carthage/Checkouts/Curry/Source/Curry.swift:9:31: warning: extraneous '_' in parameter: 'function' has no keyword argument name
~proj/Carthage/Checkouts/Curry/Source/Curry.swift:13:34: warning: extraneous '_' in parameter: 'function' has no keyword argument name
```

This was (rightfully) changed for Swift 3 it appears, right [here](https://github.com/thoughtbot/Curry/commit/ddcc3eaafb3c60df1f9a118b711331123a156918), to avoid requiring those argument labels going forward. I realize it may not be of interest or urgency to correct this issue since everything still technically works on Swift 2.x, however I figured I would post this anyway for awareness even in case another user was confused by these warnings. This being said though, it may be pretty easy to modify the generation script for these funcs to declare 2 different versions of them with swift version compiler checks (`#if swift(...)`). I _believe_ this would not result in any extraneous/duplicate overloads being actually compiled and put into the binary, so only the size of `Curry.swift` suffers. I'm interested if anyone has thoughts on this, or if it would be worth doing/accepted to make this change and PR it.

Thanks for reading! Argo and Curry are great. Cheers.

**Comment by gfontenot** [comment]
Thanks! We're definitely aware of the warnings. I actually made note of them [in my PR where I added the `_`](https://github.com/thoughtbot/Curry/pull/26). Personally, I think the warnings are a reasonable short-term compromise for compatibility with 2.X and 3.X. I'm interested to hear if they are causing any _actual_ issues for people though.

**Comment by JRHeaton** [comment]
:+1: sounds good
