### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by sa7bi** [thoughtbot/Curry#40]
Hi
Is the current version of curry support Swift 4 ?
I've tried updating my project today and keep having this error: `Ambiguous use of 'curry'`.

Thanks

**Comment by mokagio** [comment]
Related to https://github.com/thoughtbot/Curry/pull/39

**Comment by gfontenot** [comment]
Curry 4.0 has been released now, which includes a fix for the ambiguous use errors in Swift 4.
