### ISSUE TITLE
4.0.0 not available on cocoapods.org

### ISSUE THREAD

**Issue by Andrewpk** [thoughtbot/Curry#43]
It seems like cocoapods trunk needs a podspec push for this project.

**Comment by gfontenot** [comment]
Yep, that's correct. I actually lost control of the email associated with my account on cocoapods trunk, so I can't upload a new version. While I'm working on getting that fixed, you can point at master.

**Comment by gfontenot** [comment]
Good news! I own the pod again. 4.0 should now be available from the spec repo.
