### ISSUE TITLE
Does it make sense to curry in Swift?

### ISSUE THREAD

**Issue by rasmk** [thoughtbot/Curry#45]
It is actually not an issue in your code, but I would like to hear your thoughts. I hope you don't mind I open the issue.

I recently tried to write some functions for partial application of parameters to the given functions. Pretty similar to currying, but if the original function had 4 parameters, I could apply 3 and have a function that expects only one. Fewer ()s, same concept.

Played with the code a little bit and gave it up. Not because I had a problem with that, but because I thought it might be harmful.
That brings me to the original question, does it make sense to write this kind of functional goodies in Swift?

My primary reason to give it up was ARC.
With currying you retain strong references to the params in the closure. If the curried function is not consumed immediately, but retained for longer time (which often makes sense), you risk to create strong reference loops and eventually memory leaks.

To me, although Swift comes with some functional support, taking int seriously and diving deep in the functional programming seems not really an option.
What do you think. Do you take any special care, what functions and parameters you curry? Or do you ignore the problem and assume it will not happen? I am looking forward to your comments.

**Comment by GregoryMaks** [comment]
I would say it heavily depends on the situation and the architecture concepts you are using. If you are trying to incorporate some functional code into your non-functional code that everyone got used to you may face the aforementioned issues. I did too and it made me stop trying to integrate any cool functional thing I've met into the production code. 

But there are pet projects, or new architecture concepts like Redux, Lenses, etc. which are based on functional ideas and may benefit from things like currying. And there is even a full sized functional library for swift - https://github.com/typelift/Swiftz.

I think that every functionality may be of use in some cases, but also can be misused in other. Life is not a simple and the usefulness of one feature is not a binary value :). It all depends.

About retaining, there is one useful method that I've created for this:

```
public func weakify<Entity, Parameters>(method: @escaping (Entity) -> (Parameters) -> Void, of object: Entity) -> (Parameters) -> Void
    where Entity: AnyObject
{
    return { [weak object] parameters in
        object.map { method($0)(parameters) }
    }
}
```

**Comment by rasmk** [comment]
Thank you for your comment Gregory. It makes a lot of sense to me.
I come from TypeScript/JavaScript world. Spent last several months in a project with redux-like store and Angular. In JS the transition to functional feels pretty natural. As Swift offers some functional goodies, I tried to port some techniques here. Then fell into the issues and thoughts I mentioned in my original post and started wondering. Looks like your thoughts go into a similar direction... Thanks again.
