### ISSUE TITLE
SwiftPM support will be outdated on Swift 5

### ISSUE THREAD

**Issue by ikesyo** [thoughtbot/Curry#46]
This project now has a Package.swift file whose `swift-tools-version` is `3.0`, but Swift 5 drops support for Swift 3 language mode, so this package cannot be used from SwiftPM on Swift 5.

Could you update the manifest or add additional one of `Package@swift-4.swift` (or `Package@swift-4.2.swift`) and cut a new release?

Ref: https://github.com/Carthage/Carthage/issues/2694

**Comment by gfontenot** [comment]
For sure. What's the recommended solution right now? Chase the newest swift tools version? New package files for each version? I don't interact with SPM enough to know what the most reasonable way to fix the issue is.

**Comment by jshier** [comment]
@gfontenot For Alamofire we track the latest tools in `Package.swift` and use the `-swift-X` files for the lower versions of Swift we support.

**Comment by gfontenot** [comment]
Great, thanks. I'll try to work on that as soon as I have a minute (or if there are any good samaritans out there that want to open a PR, I'll review that as soon as I have a minute)

**Comment by gfontenot** [comment]
This should be fixed now with 4.0.2. Please _please_ let me know if you run into any issues on this. I don't use SPM often enough to really smoke test this.
