### ISSUE TITLE
Xcode 11 Beta 4 (Swift 5.1 run time support)

### ISSUE THREAD

**Issue by MuthurajMuthulingam** [thoughtbot/Curry#49]
Hi All, 

I'm using latest version Curry (v4.0.2) using Carthage. Having issues while building on Xcode 11 Beta 4 (11M374r). Had following issue while building
<img width="1196" alt="Screenshot 2019-08-24 at 9 45 12 pm" src="https://user-images.githubusercontent.com/10783559/63639998-80e0a980-c6b8-11e9-8990-d8fbe7dee9b4.png">

Any help here is really helpful

**Comment by gfontenot** [comment]
Beta 6 is the most recent beta. Can you confirm that this is still an issue for you when using that toolchain?

**Comment by Ferdzz** [comment]
@gfontenot I confirm that Curry v4.0.2 functions properly when using Carthage on a Swift 5 project with Xcode 11.2.1 (11B500)

**Comment by gfontenot** [comment]
I'm going to go ahead and close this then, please feel free to re-open if this is still an issue.
